version: '3'

services:
  mysql:
    build:
      context: ./docker
    image: trading-card-game/mtg-database
    ports:
      - '3307:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mtg
      MYSQL_USER: '${DB_USER:-mtg}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-mtg}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mtg-database-mysql:/var/lib/mysql'
      - ./initdb.d/import-mtg-database.sh:/docker-entrypoint-initdb.d/10-import-mtg-database.sh
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      retries: 3
      start_period: 6h
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: '${DB_USER:-mtg}'
      PMA_PASSWORD: '${DB_PASSWORD:-mtg}'
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
    mtg-database-mysql:
        driver: local